// apps/desktop/src/App.svelte
<script lang="ts">
  import ProjectSelector from '$components/ProjectSelector.svelte';
  import ProjectWorkspace from '$components/ProjectWorkspace.svelte';
  import { projectStore } from '$stores/project.svelte';
</script>

{#if projectStore.current}
  <ProjectWorkspace />
{:else}
  <ProjectSelector />
{/if}

// apps/desktop/src/App.tsx
import React from 'react';
import { ProjectSelector } from '@/lib/components/ProjectSelector';
import { ProjectWorkspace } from '@/lib/components/ProjectWorkspace';
import { useProject } from '@/lib/contexts/ProjectContext';

export function App() {
  const { current } = useProject();

  return current ? <ProjectWorkspace /> : <ProjectSelector />;
}
